// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.201
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExtensibilityCommandGroups
{
    static class Vsix
    {
        public const string Id = "ExtensibilityCommandGroups.c403e4bb-07c7-4176-8c06-955972cddaff";
        public const string Name = "Extensibility Command Groups";
        public const string Description = @"Provides base functionality for extensions targeting Visual Studio extension authors";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "vsix, vsct";
    }
}
